"""Build-time AOB signature check against the target eldenring.exe.

For every AOB our DLL scans for at runtime (tools/aob_signatures.py), verify it
resolves UNIQUELY in the game's .text. A game update that shifts code silently
breaks the runtime scans -> map injection just stops working with no diagnostic.
This catches it at build time instead.

One vanilla eldenring.exe (config game_dir) backs every profile via ModEngine
(data overlays only, no exe patch), so ONE static scan validates all profiles.

Exit codes:
  0  all critical signatures unique (non-critical misses -> warnings only)
  1  a critical signature is MISSING or AMBIGUOUS, or a drift-guard failure,
     or the exe/config could not be read.

Usage:
  py tools/check_aobs.py [--json <path>] [--exe <path>] [--all-exes]

--all-exes additionally scans every OTHER eldenring.exe build in the registry
(tools/known_exes.py, `exe_dir` in config.ini) and prints one row per signature that is
not a single match everywhere. That is the compatibility question a downpatched player
raises, and it is deliberately not part of the default build: it needs those exes on
disk, and it takes about a minute. Run it before a release, together with
scratch/run_anchor_test.py + scratch/anchor_truth.py for the RVA-anchor half.
"""
import sys, io, struct, re, argparse
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(TOOLS_DIR))
import config  # noqa: E402
from aob_signatures import SIGNATURES, check_drift  # noqa: E402
from rva_anchors import ANCHORS  # noqa: E402


def to_regex(aob):
    """Translate an AOB string ('??' = wildcard) to a byte-matching regex."""
    out = b""
    for tok in aob.split():
        out += b"." if tok == "??" else re.escape(bytes([int(tok, 16)]))
    return re.compile(out, re.DOTALL)


def load_text_section(exe_path):
    """Return (code_bytes, text_rva) for the lowest-VA .text section - the
    original MSVC code, identical on disk and in memory."""
    import pefile
    pe = pefile.PE(str(exe_path), fast_load=True)
    texts = [s for s in pe.sections if s.Name.rstrip(b"\x00") == b".text"]
    if not texts:
        raise RuntimeError("no .text section in exe")
    texts.sort(key=lambda s: s.VirtualAddress)
    t = texts[0]
    code = pe.__data__[t.PointerToRawData: t.PointerToRawData + t.SizeOfRawData]
    return code, t.VirtualAddress, t.Misc_VirtualSize


def emit_anchor_table_header():
    """src/generated_shared/goblin_anchor_table.hpp <- tools/rva_anchors.py.

    The DLL-side resolver (src/goblin_anchors.cpp) verifies every anchor's bytes at its baked
    RVA once at startup and, when the running exe is NOT the build target (a downpatch or a
    future patch), re-finds each anchor by those same bytes near the shift its neighbours
    resolved at. This header is the single bridge: the python table stays the only source.
    Written only when the content changes, so incremental builds do not recompile for nothing.
    """
    out = config.PROJECT_DIR / "src" / "generated_shared" / "goblin_anchor_table.hpp"
    lines = [
        "// AUTO-GENERATED by tools/check_aobs.py from tools/rva_anchors.py - DO NOT EDIT.",
        "// One entry per RVA anchor: baked RVA + the byte prefix that must live there",
        "// (mask 0 = wildcard). Consumed by src/goblin_anchors.cpp (the DLL) and by",
        "// scratch/anchor_resolver_test.cpp (the offline check against real exe builds).",
        "// The entry TYPE comes from the resolver itself, so there is exactly one",
        "// definition of it and no bridging between near-identical structs.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        '#include "goblin_anchor_resolve.hpp"',
        "",
        "namespace goblin::anchor_table",
        "{",
        "    using Entry = goblin::anchor_resolve::TableEntry;",
        "",
    ]
    for i, a in enumerate(ANCHORS):
        toks = a["bytes"].split()
        bs = ", ".join("0x00" if t == "??" else f"0x{int(t, 16):02X}" for t in toks)
        ms = ", ".join("0" if t == "??" else "1" for t in toks)
        lines.append(f"    inline constexpr uint8_t kB{i}[] = {{{bs}}};")
        lines.append(f"    inline constexpr uint8_t kM{i}[] = {{{ms}}};")
    lines.append("")
    lines.append("    inline constexpr Entry kEntries[] = {")
    for i, a in enumerate(ANCHORS):
        n = len(a["bytes"].split())
        lines.append(f'        {{"{a["name"]}", 0x{a["rva"]:X}, kB{i}, kM{i}, {n}}},')
    lines.append("    };")
    lines.append("    inline constexpr size_t kCount = sizeof(kEntries) / sizeof(kEntries[0]);")
    lines.append("}")
    text = "\n".join(lines) + "\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    if not out.exists() or out.read_text(encoding="utf-8") != text:
        out.write_text(text, encoding="utf-8")
        print(f"anchor table header refreshed -> {out}")


def cross_build_matrix():
    """Every signature against every exe build we hold. Returns the count of CRITICAL cells
    that are not a single match - the only thing that can block a release here, since the
    known ambiguous ones (identical twins) are documented at their entries."""
    from known_exes import known_exes, text_section
    exes = known_exes()
    others = [e for e in exes if not e.is_target]
    if not others:
        print("\n(no other exe builds configured - set exe_dir in tools/config.ini)")
        return 0
    texts = {e.version: text_section(e.path)[0] for e in exes}
    print(f"\nCross-build check: {len(SIGNATURES)} signatures x {len(exes)} builds")
    print(f"  {'signature':<34}{'crit':>5}" + "".join(f"{e.version:>8}" for e in exes))
    crit = 0
    for sig in SIGNATURES:
        rx = to_regex(sig["pattern"])
        row = []
        for e in exes:
            n = len(rx.findall(texts[e.version]))
            row.append("OK" if n == 1 else ("MISS" if n == 0 else f"x{n}"))
        if all(v == "OK" for v in row):
            continue
        print(f"  {sig['name']:<34}{'yes' if sig['critical'] else '':>5}"
              + "".join(f"{v:>8}" for v in row))
        if sig["critical"]:
            crit += sum(1 for v in row if v != "OK")
    print(f"  ---- {crit} CRITICAL cells are not a single match")
    return crit


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", help="write resolved RVAs to this JSON path")
    ap.add_argument("--exe", help="override eldenring.exe path (default: config game_dir)")
    ap.add_argument("--all-exes", action="store_true",
                    help="also scan every other exe build in the registry (slow)")
    args = ap.parse_args()

    # ---- Drift guard: every AOB literal in src/ must be in the signature list ----
    src_dir = config.PROJECT_DIR / "src"
    uncovered = check_drift(src_dir)
    if uncovered:
        print("ERROR: AOB drift - source has hex-pattern literals NOT in tools/aob_signatures.py:")
        for loc, lit in uncovered:
            print(f"  {loc}\n    {lit}")
        print("\nAdd each new AOB to tools/aob_signatures.py (name/pattern/critical) then rebuild.")
        return 1

    # ---- Locate the exe ----
    if args.exe:
        exe = Path(args.exe)
    else:
        game_dir = config.GAME_DIR
        if not game_dir:
            print("ERROR: game_dir not set in tools/config.ini (needed to locate eldenring.exe).")
            return 1
        exe = Path(game_dir) / "eldenring.exe"
    if not exe.exists():
        print(f"ERROR: eldenring.exe not found at {exe}")
        return 1

    try:
        code, text_rva, text_size = load_text_section(exe)
    except Exception as e:
        print(f"ERROR: could not read {exe}: {e}")
        return 1

    print(f"AOB check vs {exe}")
    print(f".text RVA 0x{text_rva:X}, size 0x{text_size:X}, {len(SIGNATURES)} signatures\n")
    print(f"  {'status':10} {'name':28} {'RVA':>10}  {'slot RVA':>10}")
    print(f"  {'-'*10} {'-'*28} {'-'*10}  {'-'*10}")

    results = {}
    critical_fail = False
    noncritical_warn = False

    for sig in SIGNATURES:
        rx = to_regex(sig["pattern"])
        hits = [m.start() for m in rx.finditer(code)]
        crit = sig["critical"]
        tag = "CRIT" if crit else "warn"
        entry = {"critical": crit, "matches": len(hits)}

        if len(hits) == 1:
            off = hits[0]
            rva = text_rva + off
            entry["rva"] = rva
            slot_str = ""
            if sig.get("slot"):
                disp_off, instr_len = sig["slot"]
                disp = struct.unpack_from("<i", code, off + disp_off)[0]
                slot_rva = rva + instr_len + disp
                entry["slot_rva"] = slot_rva
                slot_str = f"0x{slot_rva:X}"
            print(f"  {'[OK]':10} {sig['name']:28} {'0x%X'%rva:>10}  {slot_str:>10}")
        elif len(hits) == 0:
            entry["status"] = "MISSING"
            print(f"  {'[MISS-'+tag+']':10} {sig['name']:28} {'MISSING':>10}")
            if crit:
                critical_fail = True
            else:
                noncritical_warn = True
        else:
            entry["status"] = "AMBIGUOUS"
            print(f"  {'[AMB-'+tag+']':10} {sig['name']:28} {('x%d'%len(hits)):>10}")
            if crit:
                critical_fail = True
            else:
                noncritical_warn = True

        results[sig["name"]] = entry

    print()
    if args.json:
        import json
        Path(args.json).write_text(json.dumps(results, indent=2), encoding="utf-8")
        print(f"Wrote resolved RVAs -> {args.json}\n")

    # ---- RVA anchors: the native-menu code calls small UI helpers by direct RVA, which a
    # game update would silently redirect to unrelated code. Verify the bytes still match.
    anchor_fail = []
    if ANCHORS:
        print(f"  {'status':10} {'anchor':28} {'RVA':>10}")
        print(f"  {'-'*10} {'-'*28} {'-'*10}")
        for a in ANCHORS:
            want = a["bytes"].split()
            off = a["rva"] - text_rva
            got = code[off:off + len(want)] if 0 <= off < len(code) else b""
            ok = len(got) == len(want) and all(
                w == "??" or int(w, 16) == g for w, g in zip(want, got))
            print(f"  {('[OK]' if ok else '[BROKEN]'):10} {a['name']:28} {'0x%X' % a['rva']:>10}")
            if not ok:
                anchor_fail.append(a)
        print()
    if anchor_fail:
        print("BUILD-BLOCKING: the bytes at these RVAs changed - the game was probably updated.")
        for a in anchor_fail:
            print(f"  {a['name']} (0x{a['rva']:X}) - used by: {a['used']}")
        print("Re-find each function (Ghidra: scratch/ghidra_proj/eldenring), update the RVA in")
        print("src/ and refresh tools/rva_anchors.py (py tools/rva_anchors.py --emit 0xRVA name).")
        return 1

    emit_anchor_table_header()

    if args.all_exes and cross_build_matrix():
        print("A CRITICAL signature does not resolve on some other exe build - the mod would "
              "be broken for players on it.")
        return 1

    if critical_fail:
        print("BUILD-BLOCKING: a CRITICAL eldenring.exe signature is missing or ambiguous.")
        print("The game may have updated. Re-find the AOB (Ghidra: scratch/ghidra_proj/eldenring)")
        print("and update the source + tools/aob_signatures.py before shipping.")
        return 1
    if noncritical_warn:
        print("WARNING: a non-critical signature missed (cosmetic/niche feature may be off).")
        print("Build continues.")
    else:
        print("All signatures resolved uniquely.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
