"""Build-time AOB signature check against the target eldenring.exe.

For every AOB our DLL scans for at runtime (tools/aob_signatures.py), verify it
resolves UNIQUELY in the game's .text. A game update that shifts code silently
breaks the runtime scans -> map injection just stops working with no diagnostic.
This catches it at build time instead.

One vanilla eldenring.exe (config game_dir) backs every profile via ModEngine
(data overlays only, no exe patch), so ONE static scan validates all profiles.

Exit codes:
  0  all critical signatures unique (non-critical misses -> warnings only)
  1  a critical signature is MISSING or AMBIGUOUS, or a drift-guard failure,
     or the exe/config could not be read.

Usage:
  py tools/check_aobs.py [--json <path>] [--exe <path>] [--all-exes]

--all-exes additionally scans every OTHER eldenring.exe build in the registry
(tools/known_exes.py, `exe_dir` in config.ini) and prints one row per signature that is
not a single match everywhere. That is the compatibility question a downpatched player
raises, and it is deliberately not part of the default build: it needs those exes on
disk, and it takes about a minute. Run it before a release, together with
scratch/run_anchor_test.py + scratch/anchor_truth.py for the RVA-anchor half.
"""
import sys, io, struct, re, argparse
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")

from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
sys.path.insert(0, str(TOOLS_DIR))
import config  # noqa: E402
from aob_signatures import SIGNATURES, check_drift  # noqa: E402
from rva_anchors import ANCHORS  # noqa: E402


def to_regex(aob):
    """Translate an AOB string ('??' = wildcard) to a byte-matching regex."""
    out = b""
    for tok in aob.split():
        out += b"." if tok == "??" else re.escape(bytes([int(tok, 16)]))
    return re.compile(out, re.DOTALL)


def load_text_section(exe_path):
    """Return (code_bytes, text_rva) for the lowest-VA .text section - the
    original MSVC code, identical on disk and in memory."""
    import pefile
    pe = pefile.PE(str(exe_path), fast_load=True)
    texts = [s for s in pe.sections if s.Name.rstrip(b"\x00") == b".text"]
    if not texts:
        raise RuntimeError("no .text section in exe")
    texts.sort(key=lambda s: s.VirtualAddress)
    t = texts[0]
    code = pe.__data__[t.PointerToRawData: t.PointerToRawData + t.SizeOfRawData]
    return code, t.VirtualAddress, t.Misc_VirtualSize


def emit_anchor_table_header():
    """src/generated_shared/goblin_anchor_table.hpp <- tools/rva_anchors.py.

    The DLL-side resolver (src/goblin_anchors.cpp) verifies every anchor's bytes at its baked
    RVA once at startup and, when the running exe is NOT the build target (a downpatch or a
    future patch), re-finds each anchor by those same bytes near the shift its neighbours
    resolved at. This header is the single bridge: the python table stays the only source.
    Written only when the content changes, so incremental builds do not recompile for nothing.
    """
    out = config.PROJECT_DIR / "src" / "generated_shared" / "goblin_anchor_table.hpp"
    lines = [
        "// AUTO-GENERATED by tools/check_aobs.py from tools/rva_anchors.py - DO NOT EDIT.",
        "// One entry per RVA anchor: baked RVA + the byte prefix that must live there",
        "// (mask 0 = wildcard). Consumed by src/goblin_anchors.cpp (the DLL) and by",
        "// scratch/anchor_resolver_test.cpp (the offline check against real exe builds).",
        "// The entry TYPE comes from the resolver itself, so there is exactly one",
        "// definition of it and no bridging between near-identical structs.",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        '#include "goblin_anchor_resolve.hpp"',
        "",
        "namespace goblin::anchor_table",
        "{",
        "    using Entry = goblin::anchor_resolve::TableEntry;",
        "",
    ]
    for i, a in enumerate(ANCHORS):
        toks = a["bytes"].split()
        bs = ", ".join("0x00" if t == "??" else f"0x{int(t, 16):02X}" for t in toks)
        ms = ", ".join("0" if t == "??" else "1" for t in toks)
        lines.append(f"    inline constexpr uint8_t kB{i}[] = {{{bs}}};")
        lines.append(f"    inline constexpr uint8_t kM{i}[] = {{{ms}}};")
    lines.append("")
    lines.append("    inline constexpr Entry kEntries[] = {")
    for i, a in enumerate(ANCHORS):
        n = len(a["bytes"].split())
        lines.append(f'        {{"{a["name"]}", 0x{a["rva"]:X}, kB{i}, kM{i}, {n}}},')
    lines.append("    };")
    lines.append("    inline constexpr size_t kCount = sizeof(kEntries) / sizeof(kEntries[0]);")
    lines.append("}")
    text = "\n".join(lines) + "\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    if not out.exists() or out.read_text(encoding="utf-8") != text:
        out.write_text(text, encoding="utf-8")
        print(f"anchor table header refreshed -> {out}")
    emit_anchor_ids_header()


def emit_anchor_ids_header():
    """src/generated_shared/goblin_anchor_ids.hpp <- tools/rva_anchors.py.

    One enumerator per anchor, in table order. Call sites name the function they want and the
    RVA never leaves the table, so re-baking onto a new game build cannot desync them. The old
    scheme keyed at() BY the baked RVA: a re-bake changed every key, at() found no entry and
    answered 0, and the call sites called address 0 - silently, on every anchored path.
    """
    out = config.PROJECT_DIR / "src" / "generated_shared" / "goblin_anchor_ids.hpp"
    lines = [
        "// AUTO-GENERATED by tools/check_aobs.py from tools/rva_anchors.py - DO NOT EDIT.",
        "// The anchor each call site wants, by name. Pass one to goblin::anchors::at().",
        "// The value is the row in the table, never an address - see goblin_anchors.hpp.",
        "#pragma once",
        "#include <cstdint>",
        "",
        "namespace goblin",
        "{",
        "    enum class AnchorId : uint32_t",
        "    {",
    ]
    width = max(len(a["name"]) for a in ANCHORS)
    for i, a in enumerate(ANCHORS):
        lines.append('        %-*s = %d,' % (width, a["name"], i))
    lines.append("    };")
    lines.append("}")
    text = "\n".join(lines) + "\n"
    out.parent.mkdir(parents=True, exist_ok=True)
    if not out.exists() or out.read_text(encoding="utf-8") != text:
        out.write_text(text, encoding="utf-8")
        print(f"anchor id header refreshed -> {out}")


def check_at_call_sites():
    """No source may pass a bare number to anchors::at(). Returns the number of offenders.

    A numeric key is a silent trap: re-baking the table onto a new game build changes every
    RVA, at() then finds no entry, answers 0, and the call site calls null. The named
    constants from goblin_anchor_ids.hpp move with the table.
    """
    import re as _re
    pat = _re.compile(r"anchors::at\(\s*0[xX][0-9A-Fa-f]")
    bad = []
    for f in sorted((config.PROJECT_DIR / "src").rglob("*.?pp")):
        if f.name.startswith("goblin_anchor"):
            continue
        for n, line in enumerate(f.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
            s = line.lstrip()
            if s.startswith("//") or s.startswith("*"):
                continue
            if pat.search(line):
                bad.append("%s:%d: %s" % (f.relative_to(config.PROJECT_DIR), n, line.strip()[:90]))
    if bad:
        print("\nanchors::at() called with a raw RVA in %d place(s) - use "
              "goblin::AnchorId::<name> instead:" % len(bad))
        for b in bad:
            print("  " + b)
    return len(bad)


# Raw exe-relative addresses that are KNOWINGLY still baked, each with why it has not been
# made portable. Anything not on this list fails the build: the point is that a new one can
# never appear silently, the way V3_SLOT_VTABLE_RVA did.
RAW_ADDR_ALLOWED = {
    0x6000000:  "dllmain: a crude upper bound on the exe image, not an address",
    0x11CC530:  "in a comment only: the fault this counter was named after",
    0x2AD6688:  "PIN_VT_RVA - diagnostic compare only; RTTI resolves it (WorldMapPointPinData)",
    0x2C65D80:  "RM2 vtable FALLBACK - only used if the live capture fails",
    0x2C65D20:  "PO3 vtable FALLBACK - only used if the live capture fails",
    0x11BDE10:  "RM2 AddToTimelineSnapshot FALLBACK - only used if the AOB fails",
    0x11BDB40:  "PO3 AddToTimelineSnapshot FALLBACK - only used if the AOB fails",
}


def check_raw_exe_addresses():
    """Every baked exe-relative address in src/ that is not an anchor. Returns offender count.

    The anchors are re-found by their bytes and keyed by name, and the AOB signatures are
    checked against every exe build - but neither covers a bare `exe + 0x...` or a constant
    compared against one. That gap is not theoretical: V3_SLOT_VTABLE_RVA sat there measured on
    2.6.2, silently stopped matching on 1.17, and took the whole leak fix down with it.
    """
    import re as _re
    baked = {a["rva"] for a in ANCHORS}
    pats = (_re.compile(r"\b(?:exe|base|base_x|mod0?)\s*\+\s*0[xX]([0-9A-Fa-f]{5,8})\b"),
            _re.compile(r"constexpr\s+\w+\s+\w*(?:RVA|VTABLE|VT)\w*\s*=\s*0[xX]([0-9A-Fa-f]{5,8})\b"))
    bad = []
    for f in sorted((config.PROJECT_DIR / "src").rglob("*.?pp")):
        if f.name.startswith("goblin_anchor"):
            continue
        for n, line in enumerate(f.read_text(encoding="utf-8", errors="replace").splitlines(), 1):
            s = line.lstrip()
            if s.startswith("//") or s.startswith("*"):
                continue
            for pat in pats:
                for m in pat.finditer(line):
                    v = int(m.group(1), 16)
                    if v in baked or v in RAW_ADDR_ALLOWED:
                        continue
                    bad.append("%s:%d: 0x%X in %s"
                               % (f.relative_to(config.PROJECT_DIR), n, v, line.strip()[:70]))
    if bad:
        print("\nNEW baked exe-relative address(es) - anchor them, resolve them by RTTI, or "
              "capture them live; add to RAW_ADDR_ALLOWED with a reason only if none is possible:")
        for b in bad:
            print("  " + b)
    else:
        print("baked exe addresses: %d known, 0 new" % len(RAW_ADDR_ALLOWED))
    return len(bad)


def cross_build_matrix():
    """Every signature against every exe build we hold. Returns the count of CRITICAL cells
    that are not a single match - the only thing that can block a release here, since the
    known ambiguous ones (identical twins) are documented at their entries."""
    from known_exes import known_exes, text_section
    exes = known_exes()
    others = [e for e in exes if not e.is_target]
    if not others:
        print("\n(no other exe builds configured - set exe_dir in tools/config.ini)")
        return 0
    texts = {e.version: text_section(e.path)[0] for e in exes}
    print(f"\nCross-build check: {len(SIGNATURES)} signatures x {len(exes)} builds")
    print(f"  {'signature':<34}{'crit':>5}" + "".join(f"{e.version:>8}" for e in exes))
    crit = 0
    for sig in SIGNATURES:
        # A retired signature scans for something no code looks for any more. Checking it
        # reports failures nobody can act on, and three of the four warnings on this matrix came
        # from exactly those - noise that a real miss then has to be spotted through.
        if sig.get("retired"):
            continue
        rx = to_regex(sig["pattern"])
        row = []
        for e in exes:
            n = len(rx.findall(texts[e.version]))
            row.append("OK" if n == 1 else ("MISS" if n == 0 else f"x{n}"))
        if sig.get("ambiguous_ok") and all(v.startswith("x") for v in row):
            continue     # documented duplicate, identical on every build
        if all(v == "OK" for v in row):
            continue
        print(f"  {sig['name']:<34}{'yes' if sig['critical'] else '':>5}"
              + "".join(f"{v:>8}" for v in row))
        if sig["critical"]:
            crit += sum(1 for v in row if v != "OK")
    print(f"  ---- {crit} CRITICAL cells are not a single match")
    return crit


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--json", help="write resolved RVAs to this JSON path")
    ap.add_argument("--exe", help="override eldenring.exe path (default: config game_dir)")
    ap.add_argument("--all-exes", action="store_true",
                    help="also scan every other exe build in the registry (slow)")
    args = ap.parse_args()

    # ---- Drift guard: every AOB literal in src/ must be in the signature list ----
    src_dir = config.PROJECT_DIR / "src"
    uncovered = check_drift(src_dir)
    if uncovered:
        print("ERROR: AOB drift - source has hex-pattern literals NOT in tools/aob_signatures.py:")
        for loc, lit in uncovered:
            print(f"  {loc}\n    {lit}")
        print("\nAdd each new AOB to tools/aob_signatures.py (name/pattern/critical) then rebuild.")
        return 1

    # ---- Locate the exe ----
    if args.exe:
        exe = Path(args.exe)
    else:
        game_dir = config.GAME_DIR
        if not game_dir:
            print("ERROR: game_dir not set in tools/config.ini (needed to locate eldenring.exe).")
            return 1
        exe = Path(game_dir) / "eldenring.exe"
    if not exe.exists():
        print(f"ERROR: eldenring.exe not found at {exe}")
        return 1

    try:
        code, text_rva, text_size = load_text_section(exe)
    except Exception as e:
        print(f"ERROR: could not read {exe}: {e}")
        return 1

    print(f"AOB check vs {exe}")
    print(f".text RVA 0x{text_rva:X}, size 0x{text_size:X}, {len(SIGNATURES)} signatures\n")
    print(f"  {'status':10} {'name':28} {'RVA':>10}  {'slot RVA':>10}")
    print(f"  {'-'*10} {'-'*28} {'-'*10}  {'-'*10}")

    results = {}
    critical_fail = False
    noncritical_warn = False

    retired = [s for s in SIGNATURES if s.get("retired")]
    for sig in SIGNATURES:
        if sig.get("retired"):
            continue
        rx = to_regex(sig["pattern"])
        hits = [m.start() for m in rx.finditer(code)]
        crit = sig["critical"]
        tag = "CRIT" if crit else "warn"
        entry = {"critical": crit, "matches": len(hits)}

        if len(hits) == 1:
            off = hits[0]
            rva = text_rva + off
            entry["rva"] = rva
            slot_str = ""
            if sig.get("slot"):
                disp_off, instr_len = sig["slot"]
                disp = struct.unpack_from("<i", code, off + disp_off)[0]
                slot_rva = rva + instr_len + disp
                entry["slot_rva"] = slot_rva
                slot_str = f"0x{slot_rva:X}"
            print(f"  {'[OK]':10} {sig['name']:28} {'0x%X'%rva:>10}  {slot_str:>10}")
        elif len(hits) == 0:
            entry["status"] = "MISSING"
            print(f"  {'[MISS-'+tag+']':10} {sig['name']:28} {'MISSING':>10}")
            if crit:
                critical_fail = True
            else:
                noncritical_warn = True
        elif sig.get("ambiguous_ok"):
            # Documented duplicate: the copies are byte-identical on every build, so first-match
            # picks the same code. Printed, but it is not a finding to look past.
            entry["status"] = "AMBIGUOUS-EXPECTED"
            print(f"  {'[AMB-ok]':10} {sig['name']:28} {('x%d'%len(hits)):>10}"
                  f"   {sig['ambiguous_ok'][:60]}")
        else:
            entry["status"] = "AMBIGUOUS"
            print(f"  {'[AMB-'+tag+']':10} {sig['name']:28} {('x%d'%len(hits)):>10}")
            if crit:
                critical_fail = True
            else:
                noncritical_warn = True

        results[sig["name"]] = entry

    print()
    if args.json:
        import json
        Path(args.json).write_text(json.dumps(results, indent=2), encoding="utf-8")
        print(f"Wrote resolved RVAs -> {args.json}\n")

    # ---- RVA anchors: the native-menu code calls small UI helpers by direct RVA, which a
    # game update would silently redirect to unrelated code. Verify the bytes still match.
    anchor_fail = []
    if ANCHORS:
        print(f"  {'status':10} {'anchor':28} {'RVA':>10}")
        print(f"  {'-'*10} {'-'*28} {'-'*10}")
        for a in ANCHORS:
            want = a["bytes"].split()
            off = a["rva"] - text_rva
            got = code[off:off + len(want)] if 0 <= off < len(code) else b""
            ok = len(got) == len(want) and all(
                w == "??" or int(w, 16) == g for w, g in zip(want, got))
            print(f"  {('[OK]' if ok else '[BROKEN]'):10} {a['name']:28} {'0x%X' % a['rva']:>10}")
            if not ok:
                anchor_fail.append(a)
        print()
    if anchor_fail:
        print("BUILD-BLOCKING: the bytes at these RVAs changed - the game was probably updated.")
        for a in anchor_fail:
            print(f"  {a['name']} (0x{a['rva']:X}) - used by: {a['used']}")
        print("Re-find each function (Ghidra: scratch/ghidra_proj/eldenring), update the RVA in")
        print("src/ and refresh tools/rva_anchors.py (py tools/rva_anchors.py --emit 0xRVA name).")
        return 1

    if retired:
        print(f"\n{len(retired)} retired signature(s) - kept for the RE they document, "
              f"not scanned because no code looks for them:")
        for s in retired:
            print(f"  {s['name']}: {s['retired']}")

    emit_anchor_table_header()

    if check_raw_exe_addresses():
        print("BUILD-BLOCKING: a baked exe address that nothing re-finds at runtime.")
        return 1

    if check_at_call_sites():
        print("BUILD-BLOCKING: a call site keys anchors::at() by number, so a re-bake of")
        print("tools/rva_anchors.py silently turns that call into a call to address 0.")
        return 1

    if args.all_exes and cross_build_matrix():
        print("A CRITICAL signature does not resolve on some other exe build - the mod would "
              "be broken for players on it.")
        return 1

    if critical_fail:
        print("BUILD-BLOCKING: a CRITICAL eldenring.exe signature is missing or ambiguous.")
        print("The game may have updated. Re-find the AOB (Ghidra: scratch/ghidra_proj/eldenring)")
        print("and update the source + tools/aob_signatures.py before shipping.")
        return 1
    if noncritical_warn:
        print("WARNING: a non-critical signature missed (cosmetic/niche feature may be off).")
        print("Build continues.")
    else:
        print("All signatures resolved uniquely.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
