// AUTO-GENERATED by scratch/gen_settings_roots.py - DO NOT EDIT.
// The 5 settings MainTimeline root placements (02_040 cid0 frame1), charIds
// remapped to our injected range. Placed into the LIVE map movie (Task #4) so the
// OptionSettingTopDialog ctor's name lookups resolve. Matrix = raw bit-packed SWF
// MATRIX bytes (byte-aligned), verbatim from the settings movie.
#pragma once
#include <cstdint>
namespace goblin { namespace settings_roots_dev {
    struct RootPlace {
        const char *name;        // instance name the dialog ctor looks up
        uint16_t    newCid;      // remapped charId (registered by the def stream)
        uint16_t    oldCid;      // original settings-movie charId (reference)
        uint16_t    depth;       // display-list depth from the settings root
        const unsigned char *matrix;
        unsigned    matrixLen;
    };
    inline constexpr unsigned char ROOT_MTX_0[] = {32,59,96,159,96}; // StatusBar
    inline constexpr unsigned char ROOT_MTX_1[] = {32,150,0,84,96}; // WindowList
    inline constexpr unsigned char ROOT_MTX_2[] = {32,150,0,84,96}; // BackTabList
    inline constexpr unsigned char ROOT_MTX_3[] = {32,150,0,84,96}; // TabList
    inline constexpr unsigned char ROOT_MTX_4[] = {28,167,128,217,128}; // MenuTitle
    inline constexpr RootPlace ROOTS[] = {
        {"StatusBar", 342, 92, 3, ROOT_MTX_0, 5},
        {"WindowList", 422, 172, 6, ROOT_MTX_1, 5},
        {"BackTabList", 434, 184, 125, ROOT_MTX_2, 5},
        {"TabList", 445, 195, 156, ROOT_MTX_3, 5},
        {"MenuTitle", 448, 199, 212, ROOT_MTX_4, 5},
    };
    inline constexpr int ROOT_COUNT = 5;
} }
