#pragma once

// The anchor rebase ALGORITHM, and nothing else: no Windows, no logging, no globals.
// goblin_anchors.cpp feeds it the live module; scratch/anchor_resolver_test.cpp feeds it a
// mapped exe file, which is how this is verified against real downpatched builds instead of
// being argued about (2.6.2 / 2.6.1 / 2.6.0 / 2.2.3 / 2.2.0 - see that test).
//
// Why a rebase exists at all: a set of small engine helpers is called as `base + RVA`
// (their prologues are short and shared, so an AOB cannot pick them out). Those RVAs are
// measured on the build-target exe. On any other build they address unrelated code, and
// calling - or MinHook-patching - one corrupts the game.
//
// HOW IT DECIDES (rewritten after report 31; the previous version is the one that failed).
// The old algorithm accepted an anchor as "still at home" whenever the bytes at its baked
// RVA matched, one anchor at a time. That is not evidence of identity: clip_proxy_dtor's
// pattern occurred 3638 times in .text, so on a build where some OTHER function happened to
// start at the baked address the test passed, the resolver reported "at baked", and the mod
// called a stranger. A player's registers caught it: one anchor relocated correctly while
// its neighbour in the SAME call stayed at the baked address.
//
// So identity is established first, and position second:
//
//   1. ONE pass over .text counts how many places match each anchor's pattern.
//   2. An anchor matching EXACTLY ONCE is a PIN. Its bytes identify it, wherever they are -
//      including when that place is not the baked RVA. Pins are accepted outright.
//   3. Anything else is a FOLLOWER: either byte-identical copies exist (menu_row_item_empty
//      has 290) or the pattern is absent. A follower is never accepted on its own evidence.
//      It is placed at the match nearest to the shift its nearest PIN resolved at, within a
//      tight window - compilers keep function order and local spacing across patches - and
//      is dropped when nothing matches there.
//   4. Resolved anchors must then keep their baked ORDER; a violator is a wrong pick, and a
//      wrong address is worse than a missing one, so it is dropped.
//
// Callers treat 0 as "this feature is off on this exe". The patterns themselves are
// generated by scratch/anchor_patterns.py, which grows each one instruction by instruction
// until it matches once and wildcards the operand bytes that differ per build (rip-relative
// displacements, rel32 branch targets); 37 of the 44 reach pin status on all five builds.

#include <cstddef>
#include <cstdint>
#include <cstring>

namespace goblin::anchor_resolve
{
    // Order checking wants the resolved set in baked order; the table is generated and small,
    // so a stack buffer serves. A table larger than this simply skips the order check (every
    // anchor still had to match its own bytes) rather than allocating on a startup path.
    constexpr size_t kMaxEntries = 256;

    // How far from the predicted position a follower may be found. Measured shifts across
    // 2.6.2 / 2.6.1 / 2.6.0 / 2.2.3 / 2.2.0 span -2576..+256, so this is roughly 3x the
    // largest real one: wide enough for a bigger patch, far too narrow to reach a random
    // copy of a 290-way pattern.
    constexpr uint32_t kFollowerWindow = 0x2000;

    struct TableEntry
    {
        const char *name;
        uint32_t rva;
        const uint8_t *bytes;
        const uint8_t *mask; // 1 = compare, 0 = wildcard
        uint16_t len;
    };

    struct Image
    {
        uintptr_t base = 0;     // module base (VA)
        uintptr_t text_va = 0;  // .text start (VA)
        size_t text_len = 0;    // .text size
        uint32_t text_rva() const { return uint32_t(text_va - base); }
    };

    struct Stats
    {
        size_t at_baked = 0;
        size_t rebased = 0;
        size_t dead = 0;
        size_t order_dropped = 0;
        size_t pins = 0;       // identified by their own bytes on THIS exe
        size_t followers = 0;  // placed relative to the pins around them
        int64_t min_shift = 0;
        int64_t max_shift = 0;
    };

    struct Hit
    {
        uint32_t rva = 0;
        uint32_t count = 0;
    };

    // How many places in .text match each anchor, and where the match is when there is only
    // one. Counted for every anchor in a SINGLE pass, because the count is what separates an
    // identified function from a guess and it has to be known before anything is accepted.
    struct Census
    {
        uint32_t count = 0;
        uint32_t rva = 0; // meaningful only when count == 1
    };

    inline bool matches_at(const Image &im, uintptr_t va, const TableEntry &e)
    {
        if (va < im.text_va || va + e.len > im.text_va + im.text_len)
            return false;
        const auto *p = reinterpret_cast<const uint8_t *>(va);
        for (uint16_t i = 0; i < e.len; ++i)
            if (e.mask[i] && p[i] != e.bytes[i])
                return false;
        return true;
    }

    // Count every match of e whose RVA lies within radius of center, and keep the one
    // NEAREST to pred. This is how a follower is placed once the pins have fixed the local
    // shift; it is never used to decide whether an anchor is trustworthy.
    // No result cap: a truncated hit list could hide the true nearest.
    inline Hit find_nearest(const Image &im, const TableEntry &e, uint32_t center,
                            uint32_t radius, uint32_t pred)
    {
        Hit out{};
        const uint32_t trva = im.text_rva();
        uint64_t lo = center > radius ? uint64_t(center) - radius : 0;
        uint64_t hi = uint64_t(center) + radius;
        if (lo < trva)
            lo = trva;
        if (hi > uint64_t(trva) + im.text_len)
            hi = uint64_t(trva) + im.text_len;
        if (hi <= lo || hi - lo < e.len)
            return out;
        // Walk the first non-wildcard byte; confirm the rest only on a lead hit.
        uint16_t lead = 0;
        while (lead < e.len && !e.mask[lead])
            ++lead;
        if (lead == e.len)
            return out; // an all-wildcard pattern matches nothing meaningful
        const uint8_t first = e.bytes[lead];
        const uint8_t *p = reinterpret_cast<const uint8_t *>(im.base + lo) + lead;
        const uint8_t *end = reinterpret_cast<const uint8_t *>(im.base + hi) - (e.len - lead);
        int64_t best_d = INT64_MAX;
        while (p <= end)
        {
            const auto *f = static_cast<const uint8_t *>(
                std::memchr(p, first, size_t(end - p) + 1));
            if (!f)
                break;
            const uintptr_t va = reinterpret_cast<uintptr_t>(f) - lead;
            if (matches_at(im, va, e))
            {
                const uint32_t rva = uint32_t(va - im.base);
                ++out.count;
                const int64_t d = int64_t(rva) > int64_t(pred) ? int64_t(rva) - int64_t(pred)
                                                              : int64_t(pred) - int64_t(rva);
                if (d < best_d)
                {
                    best_d = d;
                    out.rva = rva;
                }
            }
            p = f + 1;
        }
        return out;
    }

    // Hash of a 4-byte code prefix into the census filter. Four bytes rather than two is what
    // keeps the walk cheap: MSVC prologues share their first two bytes (48 89, 48 8B) so a
    // 16-bit filter fired on a large share of .text and the per-hit table walk dominated.
    inline uint16_t prefix_hash(uint32_t k)
    {
        return uint16_t((k * 2654435761u) >> 16);
    }

    // One pass over .text for the whole table. A prefix filter turns the common case (this
    // position starts no anchor) into a load, a multiply and a bit test, so the entire table
    // is counted in a single walk for about what one AOB scan costs. An anchor whose first
    // four bytes are not all fixed cannot ride the filter and gets its own whole-.text scan
    // instead - none of ours need it, but a hand-written pattern might.
    inline void census(const Image &im, const TableEntry *tbl, size_t n, Census *out)
    {
        for (size_t i = 0; i < n; ++i)
            out[i] = Census{};
        if (!im.text_va || im.text_len < 4)
            return;

        uint64_t bm[1024] = {};
        bool filtered[kMaxEntries] = {};
        uint32_t key[kMaxEntries] = {};
        const size_t bn = n < kMaxEntries ? n : kMaxEntries;
        for (size_t i = 0; i < bn; ++i)
        {
            const auto &e = tbl[i];
            if (e.len < 4 || !e.mask[0] || !e.mask[1] || !e.mask[2] || !e.mask[3])
                continue;
            filtered[i] = true;
            std::memcpy(&key[i], e.bytes, 4);
            const uint16_t h = prefix_hash(key[i]);
            bm[h >> 6] |= uint64_t(1) << (h & 63);
        }

        const auto *p = reinterpret_cast<const uint8_t *>(im.text_va);
        const size_t len = im.text_len;
        for (size_t off = 0; off + 4 <= len; ++off)
        {
            uint32_t k = 0;
            std::memcpy(&k, p + off, 4);
            const uint16_t h = prefix_hash(k);
            if (!(bm[h >> 6] & (uint64_t(1) << (h & 63))))
                continue;
            for (size_t i = 0; i < bn; ++i)
            {
                if (!filtered[i] || key[i] != k)
                    continue;
                if (matches_at(im, im.text_va + off, tbl[i]))
                {
                    if (out[i].count == 0)
                        out[i].rva = uint32_t(im.text_rva() + off);
                    ++out[i].count;
                }
            }
        }

        // Whatever the filter could not carry, scanned the slow way so its count is real too.
        for (size_t i = 0; i < n; ++i)
        {
            if (i < kMaxEntries && filtered[i])
                continue;
            const Hit h = find_nearest(im, tbl[i],
                                       uint32_t(im.text_rva() + im.text_len / 2),
                                       uint32_t(im.text_len), tbl[i].rva);
            out[i].count = h.count;
            out[i].rva = h.rva;
        }
    }

    // The memory-file class's own vptr, derived from its resolved constructor: the target of
    // the last `lea rax,[rip+disp]` before the ctor's first real `call rel32` (a ctor writes
    // its base vtables first and its own last, then calls into member construction).
    //
    // "First call" must NOT mean "first 0xE8 byte": on the supported exe the prologue's
    // `mov rbp,r8` is 49 8B E8, and a scan that stopped on that operand byte ended before the
    // first lea - the vtable derived as 0 on EVERY exe and the menu-movie transform silently
    // served the stock movie. An 0xE8 counts as the call only when its rel32 target lands
    // inside the first .text, which is where a ctor's first real call (a base ctor, operator
    // new) always points; an operand byte's accidental "target" lands nowhere near it.
    //
    // Returns the vtable's RVA, 0 when it cannot be established. The caller still owes the
    // pointer-level sanity (slot 0 must point back into .text) - that check depends on
    // relocation state, so it stays with whoever owns the memory: the live module reads the
    // RELOCATED pointer, the offline test translates the on-disk VA through ImageBase.
    inline uint32_t derive_vtable_rva(const Image &im, uint32_t ctor_rva, uint32_t image_size)
    {
        if (!ctor_rva)
            return 0;
        // The scan window must lie inside .text, or the byte reads themselves walk off the map.
        if (uint64_t(ctor_rva) + 0x110 > uint64_t(im.text_rva()) + im.text_len)
            return 0;
        const auto *p = reinterpret_cast<const uint8_t *>(im.base + ctor_rva);
        int64_t last_lea = 0;
        for (uint32_t i = 0; i + 7 <= 0x100; ++i)
        {
            if (p[i] == 0xE8)
            {
                int32_t rel = 0;
                std::memcpy(&rel, p + i + 1, 4);
                const int64_t tgt = int64_t(ctor_rva) + i + 5 + rel;
                if (tgt >= int64_t(im.text_rva()) &&
                    tgt < int64_t(im.text_rva()) + int64_t(im.text_len))
                    break;
            }
            if (p[i] == 0x48 && p[i + 1] == 0x8D && p[i + 2] == 0x05)
            {
                int32_t disp = 0;
                std::memcpy(&disp, p + i + 3, 4);
                last_lea = int64_t(ctor_rva) + i + 7 + disp;
                i += 6;
            }
        }
        if (last_lea <= 0 || last_lea >= int64_t(image_size))
            return 0;
        return uint32_t(last_lea);
    }

    // Fill out[0..n) with the live RVA of each table entry, 0 when it could not be trusted.
    inline Stats resolve_into(const Image &im, const TableEntry *tbl, size_t n, uint32_t *out)
    {
        Stats st{};
        for (size_t i = 0; i < n; ++i)
            out[i] = 0;
        if (!im.base || !im.text_va || !im.text_len)
        {
            st.dead = n;
            return st;
        }

        // 1-2. Count first, accept only what the count identifies.
        Census cen[kMaxEntries];
        Census *pc = cen;
        if (n > kMaxEntries)
        {
            // Larger table than the stack buffer: no census is possible, so nothing can be
            // trusted. Fail closed rather than fall back to the evidence report 31 disproved.
            st.dead = n;
            return st;
        }
        census(im, tbl, n, pc);
        for (size_t i = 0; i < n; ++i)
            if (pc[i].count == 1)
            {
                out[i] = pc[i].rva;
                ++st.pins;
            }

        // 3. Followers hang off the pins. With no pin at all there is no frame of reference
        // and every remaining anchor stays unplaced - that is a foreign build we cannot read,
        // and guessing on it is what this rewrite exists to stop.
        if (st.pins)
        {
            auto predict = [&](uint32_t baked) -> uint32_t {
                int64_t best_d = INT64_MAX, shift = 0;
                for (size_t j = 0; j < n; ++j)
                    if (out[j] && pc[j].count == 1)
                    {
                        const int64_t d = int64_t(tbl[j].rva) > int64_t(baked)
                                              ? int64_t(tbl[j].rva) - int64_t(baked)
                                              : int64_t(baked) - int64_t(tbl[j].rva);
                        if (d < best_d)
                        {
                            best_d = d;
                            shift = int64_t(out[j]) - int64_t(tbl[j].rva);
                        }
                    }
                const int64_t p = int64_t(baked) + shift;
                return p < 0 ? 0u : uint32_t(p);
            };
            for (size_t i = 0; i < n; ++i)
            {
                if (out[i] || !pc[i].count)
                    continue;
                const uint32_t pred = predict(tbl[i].rva);
                const Hit h = find_nearest(im, tbl[i], pred, kFollowerWindow, pred);
                if (h.count)
                {
                    out[i] = h.rva;
                    ++st.followers;
                }
            }
        }

        // 4. Order, applied to FOLLOWERS ONLY. Compilers keep function order across patches,
        // so a follower must land between the pins that bracket it in baked order; one that
        // does not is a wrong pick from a field of identical copies, and a wrong address is
        // worse than a missing one.
        //
        // Pins are exempt on purpose. Their pattern occurs exactly once in the whole of
        // .text, so wherever it is IS the function - even if a patch moved it past a
        // neighbour. Dropping a pin for being out of order would discard proof in favour of
        // an assumption, and turn a working feature off on a build where it would have run.
        for (size_t i = 0; i < n; ++i)
        {
            if (!out[i] || pc[i].count == 1)
                continue;
            uint32_t lo = 0, hi = 0;
            int64_t lo_d = INT64_MAX, hi_d = INT64_MAX;
            for (size_t j = 0; j < n; ++j)
            {
                if (!out[j] || pc[j].count != 1)
                    continue;
                if (tbl[j].rva < tbl[i].rva)
                {
                    const int64_t d = int64_t(tbl[i].rva) - int64_t(tbl[j].rva);
                    if (d < lo_d)
                    {
                        lo_d = d;
                        lo = out[j];
                    }
                }
                else if (tbl[j].rva > tbl[i].rva)
                {
                    const int64_t d = int64_t(tbl[j].rva) - int64_t(tbl[i].rva);
                    if (d < hi_d)
                    {
                        hi_d = d;
                        hi = out[j];
                    }
                }
            }
            if ((lo && out[i] <= lo) || (hi && out[i] >= hi))
            {
                out[i] = 0;
                --st.followers;   // it was counted when placed; it is dead now
                ++st.order_dropped;
            }
        }

        for (size_t i = 0; i < n; ++i)
        {
            if (!out[i])
            {
                ++st.dead;
                continue;
            }
            if (out[i] == tbl[i].rva)
            {
                ++st.at_baked;
                continue;
            }
            ++st.rebased;
            const int64_t s = int64_t(out[i]) - int64_t(tbl[i].rva);
            if (s < st.min_shift)
                st.min_shift = s;
            if (s > st.max_shift)
                st.max_shift = s;
        }
        return st;
    }
}
