#pragma once

// The anchor rebase ALGORITHM, and nothing else: no Windows, no logging, no globals.
// goblin_anchors.cpp feeds it the live module; scratch/anchor_resolver_test.cpp feeds it a
// mapped exe file, which is how this is verified against real downpatched builds instead of
// being argued about (2.6.2 / 2.6.1 / 2.6.0 / 2.2.3 / 2.2.0 - see that test).
//
// Why a rebase exists at all: a set of small engine helpers is called as `base + RVA`
// (their prologues are short and shared, so an AOB cannot pick them out). Those RVAs are
// measured on the build-target exe. On any other build they address unrelated code, and
// calling - or MinHook-patching - one corrupts the game.
//
// HOW IT DECIDES (rewritten after report 31; the previous version is the one that failed).
// The old algorithm accepted an anchor as "still at home" whenever the bytes at its baked
// RVA matched, one anchor at a time. That is not evidence of identity: clip_proxy_dtor's
// pattern occurred 3638 times in .text, so on a build where some OTHER function happened to
// start at the baked address the test passed, the resolver reported "at baked", and the mod
// called a stranger. A player's registers caught it: one anchor relocated correctly while
// its neighbour in the SAME call stayed at the baked address.
//
// So identity is established first, and position second:
//
//   1. ONE pass over .text counts how many places match each anchor's pattern.
//   2. An anchor matching EXACTLY ONCE is a PIN. Its bytes identify it, wherever they are -
//      including when that place is not the baked RVA. Pins are accepted outright.
//   3. Anything else is a FOLLOWER: either byte-identical copies exist (menu_row_item_empty
//      has 290) or the pattern is absent. A follower is never accepted on its own evidence.
//      It is placed at the match nearest to the shift its nearest PIN resolved at, within a
//      tight window - compilers keep function order and local spacing across patches - and
//      is dropped when nothing matches there.
//   4. Resolved anchors must then keep their baked ORDER; a violator is a wrong pick, and a
//      wrong address is worse than a missing one, so it is dropped.
//
// Callers treat 0 as "this feature is off on this exe". The patterns themselves are
// generated by scratch/anchor_patterns.py, which grows each one instruction by instruction
// until it matches once and wildcards the operand bytes that differ per build (rip-relative
// displacements, rel32 branch targets); 37 of the 44 reach pin status on all five builds.
//
// The class-by-RTTI-name walk behind goblin::anchors::vtable_of lives at the end of this file
// (goblin::rtti_resolve) for the same reason: scratch/rtti_prewarm/rtti_prewarm_test.cpp runs
// it against mapped copies of real exe builds.

#include <bit>
#include <cstddef>
#include <cstdint>
#include <cstring>
#include <vector>

#include <emmintrin.h> // SSE2, part of x64 itself: the .rdata filter of the class walk

namespace goblin::anchor_resolve
{
    // Order checking wants the resolved set in baked order; the table is generated and small,
    // so a stack buffer serves. A table larger than this simply skips the order check (every
    // anchor still had to match its own bytes) rather than allocating on a startup path.
    constexpr size_t kMaxEntries = 256;

    // How far from the predicted position a follower may be found. Measured shifts across
    // 2.6.2 / 2.6.1 / 2.6.0 / 2.2.3 / 2.2.0 span -2576..+256, so this is roughly 3x the
    // largest real one: wide enough for a bigger patch, far too narrow to reach a random
    // copy of a 290-way pattern.
    constexpr uint32_t kFollowerWindow = 0x2000;

    struct TableEntry
    {
        const char *name;
        uint32_t rva;
        const uint8_t *bytes;
        const uint8_t *mask; // 1 = compare, 0 = wildcard
        uint16_t len;
    };

    struct Image
    {
        uintptr_t base = 0;     // module base (VA)
        uintptr_t text_va = 0;  // .text start (VA)
        size_t text_len = 0;    // .text size
        uint32_t text_rva() const { return uint32_t(text_va - base); }
    };

    struct Stats
    {
        size_t at_baked = 0;
        size_t rebased = 0;
        size_t dead = 0;
        size_t order_dropped = 0;
        size_t pins = 0;       // identified by their own bytes on THIS exe
        size_t followers = 0;  // placed relative to the pins around them
        int64_t min_shift = 0;
        int64_t max_shift = 0;
    };

    struct Hit
    {
        uint32_t rva = 0;
        uint32_t count = 0;
    };

    // How many places in .text match each anchor, and where the match is when there is only
    // one. Counted for every anchor in a SINGLE pass, because the count is what separates an
    // identified function from a guess and it has to be known before anything is accepted.
    struct Census
    {
        uint32_t count = 0;
        uint32_t rva = 0; // meaningful only when count == 1
    };

    inline bool matches_at(const Image &im, uintptr_t va, const TableEntry &e)
    {
        if (va < im.text_va || va + e.len > im.text_va + im.text_len)
            return false;
        const auto *p = reinterpret_cast<const uint8_t *>(va);
        for (uint16_t i = 0; i < e.len; ++i)
            if (e.mask[i] && p[i] != e.bytes[i])
                return false;
        return true;
    }

    // Count every match of e whose RVA lies within radius of center, and keep the one
    // NEAREST to pred. This is how a follower is placed once the pins have fixed the local
    // shift; it is never used to decide whether an anchor is trustworthy.
    // No result cap: a truncated hit list could hide the true nearest.
    inline Hit find_nearest(const Image &im, const TableEntry &e, uint32_t center,
                            uint32_t radius, uint32_t pred)
    {
        Hit out{};
        const uint32_t trva = im.text_rva();
        uint64_t lo = center > radius ? uint64_t(center) - radius : 0;
        uint64_t hi = uint64_t(center) + radius;
        if (lo < trva)
            lo = trva;
        if (hi > uint64_t(trva) + im.text_len)
            hi = uint64_t(trva) + im.text_len;
        if (hi <= lo || hi - lo < e.len)
            return out;
        // Walk the first non-wildcard byte; confirm the rest only on a lead hit.
        uint16_t lead = 0;
        while (lead < e.len && !e.mask[lead])
            ++lead;
        if (lead == e.len)
            return out; // an all-wildcard pattern matches nothing meaningful
        const uint8_t first = e.bytes[lead];
        const uint8_t *p = reinterpret_cast<const uint8_t *>(im.base + lo) + lead;
        const uint8_t *end = reinterpret_cast<const uint8_t *>(im.base + hi) - (e.len - lead);
        int64_t best_d = INT64_MAX;
        while (p <= end)
        {
            const auto *f = static_cast<const uint8_t *>(
                std::memchr(p, first, size_t(end - p) + 1));
            if (!f)
                break;
            const uintptr_t va = reinterpret_cast<uintptr_t>(f) - lead;
            if (matches_at(im, va, e))
            {
                const uint32_t rva = uint32_t(va - im.base);
                ++out.count;
                const int64_t d = int64_t(rva) > int64_t(pred) ? int64_t(rva) - int64_t(pred)
                                                              : int64_t(pred) - int64_t(rva);
                if (d < best_d)
                {
                    best_d = d;
                    out.rva = rva;
                }
            }
            p = f + 1;
        }
        return out;
    }

    // Hash of a 4-byte code prefix into the census filter. Four bytes rather than two is what
    // keeps the walk cheap: MSVC prologues share their first two bytes (48 89, 48 8B) so a
    // 16-bit filter fired on a large share of .text and the per-hit table walk dominated.
    inline uint16_t prefix_hash(uint32_t k)
    {
        return uint16_t((k * 2654435761u) >> 16);
    }

    // One pass over .text for the whole table. A prefix filter turns the common case (this
    // position starts no anchor) into a load, a multiply and a bit test, so the entire table
    // is counted in a single walk for about what one AOB scan costs. An anchor whose first
    // four bytes are not all fixed cannot ride the filter and gets its own whole-.text scan
    // instead - none of ours need it, but a hand-written pattern might.
    inline void census(const Image &im, const TableEntry *tbl, size_t n, Census *out)
    {
        for (size_t i = 0; i < n; ++i)
            out[i] = Census{};
        if (!im.text_va || im.text_len < 4)
            return;

        uint64_t bm[1024] = {};
        bool filtered[kMaxEntries] = {};
        uint32_t key[kMaxEntries] = {};
        const size_t bn = n < kMaxEntries ? n : kMaxEntries;
        for (size_t i = 0; i < bn; ++i)
        {
            const auto &e = tbl[i];
            if (e.len < 4 || !e.mask[0] || !e.mask[1] || !e.mask[2] || !e.mask[3])
                continue;
            filtered[i] = true;
            std::memcpy(&key[i], e.bytes, 4);
            const uint16_t h = prefix_hash(key[i]);
            bm[h >> 6] |= uint64_t(1) << (h & 63);
        }

        const auto *p = reinterpret_cast<const uint8_t *>(im.text_va);
        const size_t len = im.text_len;
        for (size_t off = 0; off + 4 <= len; ++off)
        {
            uint32_t k = 0;
            std::memcpy(&k, p + off, 4);
            const uint16_t h = prefix_hash(k);
            if (!(bm[h >> 6] & (uint64_t(1) << (h & 63))))
                continue;
            for (size_t i = 0; i < bn; ++i)
            {
                if (!filtered[i] || key[i] != k)
                    continue;
                if (matches_at(im, im.text_va + off, tbl[i]))
                {
                    if (out[i].count == 0)
                        out[i].rva = uint32_t(im.text_rva() + off);
                    ++out[i].count;
                }
            }
        }

        // Whatever the filter could not carry, scanned the slow way so its count is real too.
        for (size_t i = 0; i < n; ++i)
        {
            if (i < kMaxEntries && filtered[i])
                continue;
            const Hit h = find_nearest(im, tbl[i],
                                       uint32_t(im.text_rva() + im.text_len / 2),
                                       uint32_t(im.text_len), tbl[i].rva);
            out[i].count = h.count;
            out[i].rva = h.rva;
        }
    }

    // The memory-file class's own vptr, derived from its resolved constructor: the target of
    // the last `lea rax,[rip+disp]` before the ctor's first real `call rel32` (a ctor writes
    // its base vtables first and its own last, then calls into member construction).
    //
    // "First call" must NOT mean "first 0xE8 byte": on the supported exe the prologue's
    // `mov rbp,r8` is 49 8B E8, and a scan that stopped on that operand byte ended before the
    // first lea - the vtable derived as 0 on EVERY exe and the menu-movie transform silently
    // served the stock movie. An 0xE8 counts as the call only when its rel32 target lands
    // inside the first .text, which is where a ctor's first real call (a base ctor, operator
    // new) always points; an operand byte's accidental "target" lands nowhere near it.
    //
    // Returns the vtable's RVA, 0 when it cannot be established. The caller still owes the
    // pointer-level sanity (slot 0 must point back into .text) - that check depends on
    // relocation state, so it stays with whoever owns the memory: the live module reads the
    // RELOCATED pointer, the offline test translates the on-disk VA through ImageBase.
    inline uint32_t derive_vtable_rva(const Image &im, uint32_t ctor_rva, uint32_t image_size)
    {
        if (!ctor_rva)
            return 0;
        // The scan window must lie inside .text, or the byte reads themselves walk off the map.
        if (uint64_t(ctor_rva) + 0x110 > uint64_t(im.text_rva()) + im.text_len)
            return 0;
        const auto *p = reinterpret_cast<const uint8_t *>(im.base + ctor_rva);
        int64_t last_lea = 0;
        for (uint32_t i = 0; i + 7 <= 0x100; ++i)
        {
            if (p[i] == 0xE8)
            {
                int32_t rel = 0;
                std::memcpy(&rel, p + i + 1, 4);
                const int64_t tgt = int64_t(ctor_rva) + i + 5 + rel;
                if (tgt >= int64_t(im.text_rva()) &&
                    tgt < int64_t(im.text_rva()) + int64_t(im.text_len))
                    break;
            }
            if (p[i] == 0x48 && p[i + 1] == 0x8D && p[i + 2] == 0x05)
            {
                int32_t disp = 0;
                std::memcpy(&disp, p + i + 3, 4);
                last_lea = int64_t(ctor_rva) + i + 7 + disp;
                i += 6;
            }
        }
        if (last_lea <= 0 || last_lea >= int64_t(image_size))
            return 0;
        return uint32_t(last_lea);
    }

    // Fill out[0..n) with the live RVA of each table entry, 0 when it could not be trusted.
    inline Stats resolve_into(const Image &im, const TableEntry *tbl, size_t n, uint32_t *out)
    {
        Stats st{};
        for (size_t i = 0; i < n; ++i)
            out[i] = 0;
        if (!im.base || !im.text_va || !im.text_len)
        {
            st.dead = n;
            return st;
        }

        // 1-2. Count first, accept only what the count identifies.
        Census cen[kMaxEntries];
        Census *pc = cen;
        if (n > kMaxEntries)
        {
            // Larger table than the stack buffer: no census is possible, so nothing can be
            // trusted. Fail closed rather than fall back to the evidence report 31 disproved.
            st.dead = n;
            return st;
        }
        census(im, tbl, n, pc);
        for (size_t i = 0; i < n; ++i)
            if (pc[i].count == 1)
            {
                out[i] = pc[i].rva;
                ++st.pins;
            }

        // 3. Followers hang off the pins. With no pin at all there is no frame of reference
        // and every remaining anchor stays unplaced - that is a foreign build we cannot read,
        // and guessing on it is what this rewrite exists to stop.
        if (st.pins)
        {
            auto predict = [&](uint32_t baked) -> uint32_t {
                int64_t best_d = INT64_MAX, shift = 0;
                for (size_t j = 0; j < n; ++j)
                    if (out[j] && pc[j].count == 1)
                    {
                        const int64_t d = int64_t(tbl[j].rva) > int64_t(baked)
                                              ? int64_t(tbl[j].rva) - int64_t(baked)
                                              : int64_t(baked) - int64_t(tbl[j].rva);
                        if (d < best_d)
                        {
                            best_d = d;
                            shift = int64_t(out[j]) - int64_t(tbl[j].rva);
                        }
                    }
                const int64_t p = int64_t(baked) + shift;
                return p < 0 ? 0u : uint32_t(p);
            };
            for (size_t i = 0; i < n; ++i)
            {
                if (out[i] || !pc[i].count)
                    continue;
                const uint32_t pred = predict(tbl[i].rva);
                const Hit h = find_nearest(im, tbl[i], pred, kFollowerWindow, pred);
                if (h.count)
                {
                    out[i] = h.rva;
                    ++st.followers;
                }
            }
        }

        // 4. Order, applied to FOLLOWERS ONLY. Compilers keep function order across patches,
        // so a follower must land between the pins that bracket it in baked order; one that
        // does not is a wrong pick from a field of identical copies, and a wrong address is
        // worse than a missing one.
        //
        // Pins are exempt on purpose. Their pattern occurs exactly once in the whole of
        // .text, so wherever it is IS the function - even if a patch moved it past a
        // neighbour. Dropping a pin for being out of order would discard proof in favour of
        // an assumption, and turn a working feature off on a build where it would have run.
        for (size_t i = 0; i < n; ++i)
        {
            if (!out[i] || pc[i].count == 1)
                continue;
            uint32_t lo = 0, hi = 0;
            int64_t lo_d = INT64_MAX, hi_d = INT64_MAX;
            for (size_t j = 0; j < n; ++j)
            {
                if (!out[j] || pc[j].count != 1)
                    continue;
                if (tbl[j].rva < tbl[i].rva)
                {
                    const int64_t d = int64_t(tbl[i].rva) - int64_t(tbl[j].rva);
                    if (d < lo_d)
                    {
                        lo_d = d;
                        lo = out[j];
                    }
                }
                else if (tbl[j].rva > tbl[i].rva)
                {
                    const int64_t d = int64_t(tbl[j].rva) - int64_t(tbl[i].rva);
                    if (d < hi_d)
                    {
                        hi_d = d;
                        hi = out[j];
                    }
                }
            }
            if ((lo && out[i] <= lo) || (hi && out[i] >= hi))
            {
                out[i] = 0;
                --st.followers;   // it was counted when placed; it is dead now
                ++st.order_dropped;
            }
        }

        for (size_t i = 0; i < n; ++i)
        {
            if (!out[i])
            {
                ++st.dead;
                continue;
            }
            if (out[i] == tbl[i].rva)
            {
                ++st.at_baked;
                continue;
            }
            ++st.rebased;
            const int64_t s = int64_t(out[i]) - int64_t(tbl[i].rva);
            if (s < st.min_shift)
                st.min_shift = s;
            if (s > st.max_shift)
                st.max_shift = s;
        }
        return st;
    }
}

// ---------------------------------------------------------------------------------------
// A class's vtable, found by its RTTI name (the walk goblin::anchors::vtable_of runs).
//
// MSVC leaves a handle no patch moves: one qword BEFORE a vtable sits a pointer to the class's
// _RTTICompleteObjectLocator, and the locator names the class through its TypeDescriptor.
// Walking that backwards - name -> TypeDescriptor -> locator -> vtable - finds the class
// wherever the linker put it this time. The acceptance rules are the ones this walk has always
// had: exactly one place holds the name, and exactly one .rdata qword points at a locator of
// that TypeDescriptor. Anything else answers 0.
//
// What changed on 2026-09-23 is the cost. The first lookup of each name used to walk every
// section byte by byte - the whole 99 MB image for the name, .rdata again for the locator and
// again for the vtable - 65-90 ms PER NAME, and two of those ran on the game's UI thread the
// first time the settings screen opened over the map: one 186 ms frame. Now:
//   - The name is looked for only in writable, non-executable sections. A TypeDescriptor is a
//     writable object (its spare field caches the undecorated name at run time), so it is never
//     emitted into code or read-only data. On every build we hold (2.2.0 .. 2.7.1) all 12035
//     decorated class names sit in .data and nowhere else, so skipping the rest (.text, .rdata
//     and the small ones: 85 of the 99 MB) changes no answer - scratch/rtti_prewarm/ has the
//     census and the old-against-new comparison.
//   - memchr finds the name's first-byte candidates, and the two .rdata walks skip, 16 offsets
//     at a time, every offset that cannot hold a wanted value (each_candidate), instead of a
//     compare at every byte. Every offset that COULD still gets the exact compare, unaligned
//     ones included, so the matches are the same set the byte-by-byte walk found.
//   - Any number of names share the same three walks (names, locators, vtables), so the whole
//     list costs about what one name does alone.
namespace goblin::rtti_resolve
{
    struct Section
    {
        uint32_t rva = 0;
        uint32_t len = 0;       // VirtualSize - what the loader mapped
        bool name_home = false; // writable and not executable: where a TypeDescriptor can live
        bool rdata = false;     // named ".rdata": where the locators and the vtables live
    };

    // The section table, read from the module's own headers by offset (no Windows types, so
    // the offline test runs this very function on its mapped copies).
    inline std::vector<Section> sections_of(uintptr_t base)
    {
        std::vector<Section> out;
        if (!base)
            return out;
        const auto *img = reinterpret_cast<const uint8_t *>(base);
        uint32_t e_lfanew = 0;
        std::memcpy(&e_lfanew, img + 0x3C, 4);
        const uint8_t *nt = img + e_lfanew;
        uint16_t nsec = 0, opt_size = 0;
        std::memcpy(&nsec, nt + 6, 2);      // FileHeader.NumberOfSections
        std::memcpy(&opt_size, nt + 20, 2); // FileHeader.SizeOfOptionalHeader
        const uint8_t *sh = nt + 24 + opt_size;
        out.reserve(nsec);
        for (uint16_t i = 0; i < nsec; ++i, sh += 40)
        {
            uint32_t vsize = 0, va = 0, ch = 0;
            std::memcpy(&vsize, sh + 8, 4);
            std::memcpy(&va, sh + 12, 4);
            std::memcpy(&ch, sh + 36, 4);
            Section s{};
            s.rva = va;
            s.len = vsize;
            s.name_home = (ch & 0x80000000u) && !(ch & 0x20000000u); // MEM_WRITE, not MEM_EXECUTE
            s.rdata = std::memcmp(sh, ".rdata", 7) == 0;               // the NUL too: exactly ".rdata"
            out.push_back(s);
        }
        return out;
    }

    // Per batch. A longer list is resolved in batches of kMaxNames. More valid locators in one
    // batch than kMaxLocators makes the names that overflowed answer 0 (fail closed); the
    // classes looked up here have one locator each, so neither limit is anywhere near.
    constexpr size_t kMaxNames = 64;
    constexpr size_t kMaxLocators = 256;

    // Up to this many keys, the .rdata walks filter with SSE2; above it, with the dword hash.
    constexpr size_t kVectorKeys = 8;

    inline uint16_t dword_hash(uint32_t k)
    {
        return uint16_t((k * 2654435761u) >> 16);
    }

    // Call fn(off) for every offset in [0, len - width] at which one of the keys MAY start;
    // fn makes the exact comparison. This only skips offsets that cannot hold a key, so the
    // set of matches is exactly what a compare at every byte finds - unaligned ones included.
    //   - A few keys (the list at init, or one name on its own): SSE2, 16 offsets per step,
    //     on bytes 1 and 2 of each key. Those are the informative ones: byte 0 of a
    //     TypeDescriptor RVA or a locator address is a multiple of 4, and the high bytes are
    //     the ones most of .rdata shares (every RVA there is 0x02xxxxxx..0x04xxxxxx, every
    //     pointer 0x00007FFxxxxxxxxx).
    //   - Many keys (the offline test's batches): a hash of the dword at each offset against a
    //     64K-bit table - a load, a multiply and a bit test for a position that holds no key.
    // width is the key size, 4 or 8 bytes.
    template <typename F>
    inline void each_candidate(const uint8_t *p, size_t len, size_t width, const uint64_t *keys,
                               size_t nk, F &&fn)
    {
        if (!nk || width < 4 || len < width)
            return;
        const size_t last = len - width; // the last offset a whole key fits at
        if (nk > kVectorKeys)
        {
            uint64_t bm[1024] = {};
            for (size_t j = 0; j < nk; ++j)
            {
                const uint16_t h = dword_hash(uint32_t(keys[j]));
                bm[h >> 6] |= uint64_t(1) << (h & 63);
            }
            for (size_t off = 0; off <= last; ++off)
            {
                uint32_t lo = 0;
                std::memcpy(&lo, p + off, 4);
                const uint16_t h = dword_hash(lo);
                if (bm[h >> 6] & (uint64_t(1) << (h & 63)))
                    fn(off);
            }
            return;
        }
        uint8_t b1[kVectorKeys] = {}, b2[kVectorKeys] = {};
        __m128i v1[kVectorKeys], v2[kVectorKeys];
        for (size_t j = 0; j < nk; ++j)
        {
            b1[j] = uint8_t(keys[j] >> 8);
            b2[j] = uint8_t(keys[j] >> 16);
            v1[j] = _mm_set1_epi8(char(b1[j]));
            v2[j] = _mm_set1_epi8(char(b2[j]));
        }
        size_t off = 0;
        // One step tests starts off..off+15 and reads p[off+1 .. off+17], so it needs
        // off + 18 <= len; a start past `last` is dropped, and the tail finishes byte by byte.
        for (; off + 18 <= len; off += 16)
        {
            const __m128i a = _mm_loadu_si128(reinterpret_cast<const __m128i *>(p + off + 1));
            const __m128i b = _mm_loadu_si128(reinterpret_cast<const __m128i *>(p + off + 2));
            __m128i m = _mm_setzero_si128();
            for (size_t j = 0; j < nk; ++j)
                m = _mm_or_si128(m, _mm_and_si128(_mm_cmpeq_epi8(a, v1[j]),
                                                  _mm_cmpeq_epi8(b, v2[j])));
            unsigned bits = unsigned(_mm_movemask_epi8(m));
            while (bits)
            {
                const size_t at = off + size_t(std::countr_zero(bits));
                if (at <= last)
                    fn(at);
                bits &= bits - 1;
            }
        }
        for (; off <= last; ++off)
            for (size_t j = 0; j < nk; ++j)
                if (p[off + 1] == b1[j] && p[off + 2] == b2[j])
                {
                    fn(off);
                    break;
                }
    }

    inline void find_vtables_batch(uintptr_t base, const Section *secs, size_t nsec,
                                   const char *const *names, size_t n, uint32_t *out)
    {
        size_t nlen[kMaxNames] = {};
        uint32_t td_rva[kMaxNames] = {};
        uint32_t td_hits[kMaxNames] = {};
        uint32_t vt_rva[kMaxNames] = {};
        uint32_t vt_hits[kMaxNames] = {};
        bool overflow[kMaxNames] = {};
        for (size_t i = 0; i < n; ++i)
        {
            out[i] = 0;
            // The NUL is part of the needle: it keeps a prefix of a longer name from matching.
            nlen[i] = names[i] && names[i][0] ? std::strlen(names[i]) + 1 : 0;
        }

        // 1. The name string -> the TypeDescriptor that owns it (the name sits at +0x10).
        //    One memchr walk per distinct first byte - every decorated name starts with '.'.
        bool walked[256] = {};
        for (size_t i = 0; i < n; ++i)
        {
            if (!nlen[i])
                continue;
            const uint8_t c = uint8_t(names[i][0]);
            if (walked[c])
                continue;
            walked[c] = true;
            for (size_t s = 0; s < nsec; ++s)
            {
                if (!secs[s].name_home)
                    continue;
                const auto *p = reinterpret_cast<const uint8_t *>(base + secs[s].rva);
                const size_t len = secs[s].len;
                size_t off = 0;
                while (off < len)
                {
                    const auto *f = static_cast<const uint8_t *>(std::memchr(p + off, c, len - off));
                    if (!f)
                        break;
                    off = size_t(f - p);
                    for (size_t j = 0; j < n; ++j)
                    {
                        if (!nlen[j] || uint8_t(names[j][0]) != c || nlen[j] > len - off ||
                            std::memcmp(f, names[j], nlen[j]) != 0)
                            continue;
                        const uint64_t rva = uint64_t(secs[s].rva) + off;
                        if (rva >= 0x10)
                        {
                            td_rva[j] = uint32_t(rva - 0x10);
                            ++td_hits[j];
                        }
                    }
                    ++off;
                }
            }
        }

        // 2. Every .rdata reference to a TypeDescriptor, keeping only the ones that really are
        //    its locator. The TypeDescriptor RVA appears TWICE per class: in the
        //    _RTTICompleteObjectLocator (pTypeDescriptor at +12) and in the
        //    _RTTIBaseClassDescriptor (pTypeDescriptor at +0); demanding a single reference is
        //    what once made every class answer "not found" on a live 2.7.0. The x64 locator
        //    identifies itself: signature 1 at +0, and pSelf at +20 holding its OWN rva.
        uint64_t keys[kMaxLocators > kMaxNames ? kMaxLocators : kMaxNames];
        size_t nk = 0;
        for (size_t i = 0; i < n; ++i)
            if (td_hits[i] == 1)
                keys[nk++] = td_rva[i];
        struct Locator
        {
            uint64_t va; // absolute, as the relocated pointer before a vtable holds it
            size_t name;
        };
        Locator loc[kMaxLocators];
        size_t nloc = 0;
        for (size_t s = 0; nk && s < nsec; ++s)
        {
            if (!secs[s].rdata)
                continue;
            const auto *p = reinterpret_cast<const uint8_t *>(base + secs[s].rva);
            const size_t len = secs[s].len;
            const uint32_t sec_rva = secs[s].rva;
            each_candidate(p, len, 4, keys, nk, [&](size_t off) {
                uint32_t k = 0;
                std::memcpy(&k, p + off, 4);
                for (size_t i = 0; i < n; ++i)
                {
                    if (td_hits[i] != 1 || td_rva[i] != k)
                        continue;
                    if (off < 12 || off - 12 + 24 > len)
                        continue; // a locator is 24 bytes; do not read past the section
                    const uint32_t col_rva = uint32_t(sec_rva + off - 12);
                    uint32_t sig = 0, self = 0;
                    std::memcpy(&sig, reinterpret_cast<const void *>(base + col_rva), 4);
                    std::memcpy(&self, reinterpret_cast<const void *>(base + col_rva + 20), 4);
                    if (sig != 1 || self != col_rva)
                        continue; // a base-class descriptor, not the locator
                    if (nloc == kMaxLocators)
                    {
                        overflow[i] = true;
                        continue;
                    }
                    loc[nloc++] = Locator{uint64_t(base) + col_rva, i};
                }
            });
        }

        // 3. The vtable is one qword after whatever points at a locator.
        for (size_t l = 0; l < nloc; ++l)
            keys[l] = loc[l].va;
        for (size_t s = 0; nloc && s < nsec; ++s)
        {
            if (!secs[s].rdata)
                continue;
            const auto *p = reinterpret_cast<const uint8_t *>(base + secs[s].rva);
            const uint32_t sec_rva = secs[s].rva;
            each_candidate(p, secs[s].len, 8, keys, nloc, [&](size_t off) {
                uint64_t k = 0;
                std::memcpy(&k, p + off, 8);
                for (size_t l = 0; l < nloc; ++l)
                    if (loc[l].va == k)
                    {
                        vt_rva[loc[l].name] = uint32_t(sec_rva + off + 8);
                        ++vt_hits[loc[l].name];
                    }
            });
        }

        for (size_t i = 0; i < n; ++i)
            out[i] = (td_hits[i] == 1 && !overflow[i] && vt_hits[i] == 1) ? vt_rva[i] : 0;
    }

    // out[i] = the RVA of names[i]'s vtable, 0 when it is absent or ambiguous. `base` is the
    // module as the loader mapped AND relocated it: a vtable's locator pointer is compared as
    // an absolute address. Pass the decorated names exactly as the exe spells them.
    inline void find_vtables(uintptr_t base, const Section *secs, size_t nsec,
                             const char *const *names, size_t n, uint32_t *out)
    {
        for (size_t first = 0; first < n; first += kMaxNames)
            find_vtables_batch(base, secs, nsec, names + first,
                               n - first < kMaxNames ? n - first : kMaxNames, out + first);
    }
}
